# This is a basic workflow to help you get started with Actions
name: Homepage Deploy
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, page_deploy ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  page_deploy:
    runs-on: ubuntu-latest
    steps:
    # >>> generate pdf >>>
      - name: Change to master
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Checkout submodules # checkout rest
        shell: bash
        run: |
          # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
          git config --global url."https://github.com/".insteadOf "git@github.com:"
          auth_header="$(git config --local --get http.https://github.com/.extraheader)"
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          pre_compile: |
              apk add msttcorefonts-installer fontconfig
              update-ms-fonts
              fc-cache -f
      - name: Save generated pdf to /tmp
        run: |
          cp main.pdf /tmp
      - name: Change to page_deploy
        uses: actions/checkout@v2
        with:
          ref: 'page_deploy'
      - name: Copy generated pdf to workdir
        run: |
          mv /tmp/main.pdf docs/main.pdf
          rm -rf hfutbadges
    # <<< generate pdf <<<

    # >>> build page >>>
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs
      - name: Update gh-pages
        run: |
          git fetch origin gh-pages:gh-pages
          mkdocs gh-deploy --config-file ./mkdocs.yml
    # <<< build page <<<
